object Test:
  scala.util.boundary.break(1) // error
